teensy:
  vid: 0x16C0
  baudrate: 9600
  timeout: 1.0
  enable_fallback: true

projector:
  spi_max_speed: 125000000
  num_pixels_x: 2560
  num_pixels_y: 1440

chamber:
  temp: 40
  valid_diff: 5

recoater:
  temp: 40
  valid_diff: 5
  vertical_pullback: 2
  clear_pos: 140

reservoir:
  extrude_multiple: 1.1

files:
  app_name: metal_resin_printer
  state_file_name: state_file

display:
  width: 240
  height: 240